### PR TITLE
Add Laravel 5.7 Support

### PR DESCRIPTION
**Pull request by SalemCode8**

### CODE REVIEW

**Comment by dangermark** [comment]
Please check previous pull requests before creating a new one. This is the 4th PR for 5.7 support.

**Comment by SalemCode8** [comment]
Yeah i saw this, but why no one of this 4 PR got merged ?
it's tested with L5.7 and it's working fine

**Comment by bumbummen99** [comment]
Well the tests will fail with 5.7 as the Illuminate Auth Logout Event has changed its constructors signature.

**Comment by SalemCode8** [comment]
I already made a clone package using it just i changed the laravel support versions to add 5.7 and i tested it and it's working fine

**Comment by bumbummen99** [comment]
@SalemCode8 https://github.com/Crinsane/LaravelShoppingcart/pull/541#issuecomment-451149266

https://github.com/Crinsane/LaravelShoppingcart/blob/7ff157b7e1ef10d27cd2759d5151aae2cc6b1b9a/tests/CartTest.php#L916

**Comment by Crinsane** [comment]
Never version has been tagged. https://github.com/Crinsane/LaravelShoppingcart/releases/tag/2.6.0 Sorry for the delay, but life got in the way.

**Pull request closed without merging**
