### PR TITLE
Update composer.json

### PR DESCRIPTION
**Pull request by bitw**
support Laravel 5.7

### CODE REVIEW

**Review by mohammed-adil-moughal — COMMENTED** [review]
why not just ad a 5.* fro all versions of 5? cant that work?

**Review by mohammed-adil-moughal — APPROVED** [review]

**Comment by bitw** [comment]
@mohammed-adil-moughal Does not work with version 5.0

**Comment by remiheens** [comment]
UP ! @Crinsane when accepting this pull request ?

**Comment by georgeboot** [comment]
@bitw Then why don't do `^5.1` as a constraint? Laravel seems to respect semantic versioning in their illuminate packages now (no non-backwards compatible changes in minor versions).

**Pull request closed without merging**
