### PR TITLE
added support laravel5.7*

### PR DESCRIPTION
**Pull request by dionatanmelo1**

### CODE REVIEW

**Comment by lloricode** [comment]
already done this, but not already merge

**Comment by ELBANNA179** [comment]
please help me  dosn't work with 5.5 i need it !!!!!!!!

**Comment by jsdecena** [comment]
There are no tests confirming everything works well w L5.7?

**Comment by SalemCode8** [comment]
everything is working fine with laravel 5.7, but you can't install it because of laravel required version in composer.json file i forked the repo and created a new package on packagist so anyone can install it with L5.7 you can install it using this command

`composer require salemcode8/shoppingcart`

it's the same i just changed the Laravel supported version and added 5.7 if the composer conflicted with you as it did with me by install V2.5.0
just add 

`"salemcode8/shoppingcart": "^2.6"`

 in the requires of

`composer.json`

and run

`composer update`

and you will got it

**Comment by Crinsane** [comment]
Never version has been tagged. https://github.com/Crinsane/LaravelShoppingcart/releases/tag/2.6.0 Sorry for the delay, but life got in the way.

**Comment by jsdecena** [comment]
@Crinsane Yup. Thanks for this!

**Pull request closed without merging**
