### PR TITLE
Updated for laravel 5.7

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by siteclub** [comment]
Done

**Comment by lloricode** [comment]
please see duplicate before PR, this is duplicate

**Comment by bumbummen99** [comment]
The tests will fail, the Illuminate\Auth\Events\Logout constructor requires a string as the first parameter from 5.7+ on.

5.6 https://laravel.com/api/5.6/Illuminate/Auth/Events/Logout.html#method___construct
5.7 https://laravel.com/api/5.7/Illuminate/Auth/Events/Logout.html#method___construct

**Comment by Crinsane** [comment]
Newer version has been tagged. https://github.com/Crinsane/LaravelShoppingcart/releases/tag/2.6.0 Sorry for the delay, but life got in the way.

**Pull request closed without merging**
