### PR TITLE
Add total price quantity in CartItem

### PR DESCRIPTION
**Pull request by tiagocardosoweb**
Lets add the total price of a item based on quantity.

### CODE REVIEW

**Comment by peterquentin** [comment]
@tiagocardosoweb we have $cartItem->subtotal and $cartItem->subtotal() for this? what am I missing?

**Comment by tiagocardosoweb** [comment]
$cartItem->subtotal = based without "TAX"
If you have 20x a item and if you want want to know the price? You are not going to use total or subtotal because It may have other products. Thats why you need a price based on qty :)

**Comment by peterquentin** [comment]
@tiagocardosoweb that's right it without the tax just like your code: 
$this->qty_price = $this->price * $this->qty;

I'm still not seeing the difference, perhaps you can tell me if you get different results running $cartItem->subtotal() and $cartItem->qty_price().

**Comment by tiagocardosoweb** [comment]
Hummm, thinking better I'm not 100% sure but If it's possible to use $cartItem->subtotal / total then it's the same, when I created this Issue I had idea that subtotal and total only worked with Cart::method, but for give you a 100% accurate answer I need to test it again, at least I had a look and seems what I have created is duplicated. 👍

**Pull request closed without merging**
