### PR TITLE
Removed conditional that would return a CartItem. 

### PR DESCRIPTION
**Pull request by garrensweet**
Instead, the search method will always return a collection.

### CODE REVIEW

**Comment by Crinsane** [comment]
Please update the tests to reflect the changes made

**Comment by garrensweet** [comment]
Oops, sorry about that. I'll fix it now.

**Comment by Crinsane** [comment]
@garrensweet Have you had time to update the tests? So I can merge this. :)

**Comment by garrensweet** [comment]
@Crinsane Hey! Sorry for the delay here, long days kept me from being able to modify the unit tests. Things should be good now and all tests should be correctly passing. Please let me know if anything needs adjusting.

**Comment by Crinsane** [comment]
This has been changed.

**Pull request closed without merging**
