### PR TITLE
Laravel 5.8 compatibility

### PR DESCRIPTION
**Pull request by lloricode**
Laravel 5.8 compatibility, and update unit test with deprecated assertion (wip).

also wait to merge [this](https://github.com/Crinsane/LaravelShoppingcart/pull/549) to fix the failed assert.

### CODE REVIEW

**Comment by MoogyG** [comment]
I don't understand why it takes so long to merge this.
I really respect your work @Crinsane but if you don't want to manage this package anymore, please edit your README and add "deprecated".

**Comment by agjmills** [comment]
:+1:

**Comment by devarda** [comment]
+1

**Comment by lloricode** [comment]
this is so _loooooooooooooooooooooooooooooooooooong_

**Comment by lloricode** [comment]
guys you can use this https://github.com/darryldecode/laravelshoppingcart,

**Comment by lloricode** [comment]
Resolve #548

**Pull request closed without merging**
