### PR TITLE
Laravel 5.7 Support

### PR DESCRIPTION
**Pull request by lloricode**

### CODE REVIEW

**Comment by lloricode** [comment]
already done  https://github.com/Crinsane/LaravelShoppingcart/pull/494

**Comment by chrisjohnstone** [comment]
Excuse my lack of knowledge but after updating the package `composer.json`, running `composer update` still returns the error that the package cannot be installed.

Am I missing something?

**Comment by AlexMac7** [comment]
@chrisjohnstone 
The PR has been submitted but hasn't been merged yet.

If you need to you can fork the repository, update the composer.json then reference your forked repository in your composer.json.

That is what I'm doing at the moment until #494 is accepted and merged.

http://tech.osteel.me/posts/2015/08/10/how-to-use-the-fork-of-a-repository-with-composer.html

**Comment by chrisjohnstone** [comment]
@AlexMac7 Thanks! Got it working.

**Comment by AlexMac7** [comment]
@chrisjohnstone Glad to hear it :)

**Pull request closed without merging**
