### PR TITLE
Update composer.json

### PR DESCRIPTION
**Pull request by juelrana**

### CODE REVIEW

**Comment by lloricode** [comment]
duplicate

**Comment by jasonmccreary** [comment]
With respect, this is the ninth _Upgrade to 5.7_ PR. Seems it's not passing a test. Curious why this still hasn't been fixed as clearly there is demand.

Asking because I'm reluctant to open the tenth, but if I were to open a *passing* PR, would it actually be merged?

**Comment by Crinsane** [comment]
Newer version has been tagged. https://github.com/Crinsane/LaravelShoppingcart/releases/tag/2.6.0 Sorry for the delay, but life got in the way.

**Comment by hardevine** [comment]
wassup @Crinsane , long time no see

**Pull request closed without merging**
