### PR TITLE
adds ability to copy content between instances

### PR DESCRIPTION
**Pull request by mateusjatenee**
did this in a hurry — there may be some minor mistakes  \

Basically allows an user to copy content between instances, for example from wishlist to default.

### CODE REVIEW

**Comment by mateusjatenee** [comment]
Hi? @Crinsane

**Comment by mateusjatenee** [comment]
uh... hello? @Crinsane

**Comment by huglester** [comment]
@Crinsane any luck with this?

**Comment by Crinsane** [comment]
Closing to clean up some old stuff. If this is still a desired feature, please create a new issue or PR. Sorry

**Pull request closed without merging**
