### PR TITLE
Adding support for 5.7

### PR DESCRIPTION
**Pull request by blaisedufrain**

### CODE REVIEW

**Comment by Crinsane** [comment]
Newer version has been tagged. https://github.com/Crinsane/LaravelShoppingcart/releases/tag/2.6.0 Sorry for the delay, but life got in the way.

**Comment by trippo** [comment]
Please update packagist

**Comment by trippo** [comment]
@Crinsane

**Comment by Crinsane** [comment]
@trippo Should be updated

**Comment by trippo** [comment]
thanks

**Pull request closed without merging**
